-- MySQL Script generated by MySQL Workbench
-- Wed Mar 20 11:05:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cmaps
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cmaps` ;

-- -----------------------------------------------------
-- Schema cmaps
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cmaps` ;
USE `cmaps` ;

-- -----------------------------------------------------
-- Table `cmaps`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmaps`.`course` (
  `courseCode` VARCHAR(255) NOT NULL,
  `courseTitle` VARCHAR(255) NOT NULL,
  `courseOutline` TEXT NULL DEFAULT NULL,
  `prerequisites` TEXT NULL DEFAULT NULL,
  `learningoutcomes` TEXT NULL DEFAULT NULL,
  `creditHrs` INT NULL,
  `evaluation` TEXT NULL DEFAULT NULL,
  `availability` VARCHAR(45) NULL,
  `program` VARCHAR(45) NULL,
--  FOREIGN KEY (`program`) REFERENCES `program`(`programCode`),
  PRIMARY KEY (`courseCode`));


-- -----------------------------------------------------
-- Table `cmaps`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cmaps`.`login` (
  `id`               INTEGER NOT NULL AUTO_INCREMENT,
  `username`         VARCHAR(45) NOT NULL,
  `hashedPassword`   VARCHAR(255) NOT NULL,
--  `userType`         INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `cmaps`.`program` (
   `programName`     VARCHAR(256) NOT NULL,
   `programCode`     VARCHAR(12)   NOT NULL,
   `programOutline`  TEXT NOT NULL,
   `requiredCourses` TEXT NULL,
   PRIMARY KEY(`programCode`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
